### ISSUE TITLE
无法使用docker search

### ISSUE THREAD

**Issue by zhaoqi9** [jonssonyan/cf-workers-proxy#3]
使用docker search ubuntu返回如下信息：
Error response from daemon: Get "https://index.docker.io/v1/search?q=ubuntu&n=25": dial tcp 109.160.167.165:443: i/o timeout
更换DNS也不行。

**Comment by jonssonyan** [comment]
![image](https://github.com/user-attachments/assets/f207cdcd-eee0-4191-b1a5-93f0aeb38d02)
README.md 里面写了，搜索要加前缀不然代理不了
