### ISSUE TITLE
docker pull exception

### ISSUE THREAD

**Issue by HimmaTong** [jonssonyan/cf-workers-proxy#4]
I used docker pull thrower exception after deploy this worker ： repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Comment by jonssonyan** [comment]
repository does not exist or may require 'docker login': denied

**Comment by HimmaTong** [comment]
> > repository does not exist or may require 'docker login': denied
> 
> 一看你就是被他唬住了，他发英文 你也发英文 其实他也是国人

我只是想秀一下我的词典笔，竟然被你发现了。。。老外也不用想方设法的去墙外看看。
